language: python
python:
  - 2.7

sudo: required

os:
  - linux

services:
  - docker

env:
  matrix:
#  - DRAKE_VERSION="20181212"
  - DRAKE_VERSION="20190125"

install:
  - docker build -t mit6881 -f ubuntu16_04_mit6881.dockerfile --build-arg DRAKE_VERSION=$DRAKE_VERSION .

script:
  - python ./docker_run.py --os linux --entrypoint /6-881-examples/run_tests.sh
